// App Store Categories (iOS)
export const APP_STORE_CATEGORIES = {
  Books: [],
  Business: [],
  "Developer Tools": [],
  Education: [],
  Entertainment: [],
  Finance: [],
  "Food & Drink": [],
  Games: [
    "Action",
    "Adventure",
    "Arcade",
    "Board",
    "Card",
    "Casino",
    "Dice",
    "Educational",
    "Family",
    "Music",
    "Puzzle",
    "Racing",
    "Role Playing",
    "Simulation",
    "Sports",
    "Strategy",
    "Trivia",
    "Word",
  ],
  "Graphics & Design": [],
  "Health & Fitness": [],
  Lifestyle: [],
  "Magazines & Newspapers": [],
  Medical: [],
  Music: [],
  Navigation: [],
  News: [],
  "Photo & Video": [],
  Productivity: [],
  Reference: [],
  Shopping: [],
  "Social Networking": [],
  Sports: [],
  Travel: [],
  Utilities: [],
  Weather: [],
} as const

// Google Play Categories (Android)
export const GOOGLE_PLAY_CATEGORIES = {
  "Art & Design": [],
  "Auto & Vehicles": [],
  Beauty: [],
  "Books & Reference": [],
  Business: [],
  Comics: [],
  Communication: [],
  Dating: [],
  Education: [],
  Entertainment: [],
  Events: [],
  Finance: [],
  "Food & Drink": [],
  "Health & Fitness": [],
  "House & Home": [],
  "Libraries & Demo": [],
  Lifestyle: [],
  "Maps & Navigation": [],
  Medical: [],
  "Music & Audio": [],
  "News & Magazines": [],
  Parenting: [],
  Personalization: [],
  Photography: [],
  Productivity: [],
  Shopping: [],
  Social: [],
  Sports: [],
  Tools: [],
  "Travel & Local": [],
  "Video Players & Editors": [],
  Weather: [],
  Games: [
    "Action",
    "Adventure",
    "Arcade",
    "Board",
    "Card",
    "Casino",
    "Casual",
    "Educational",
    "Music",
    "Puzzle",
    "Racing",
    "Role Playing",
    "Simulation",
    "Sports",
    "Strategy",
    "Trivia",
    "Word",
  ],
} as const

// Countries with their codes
export const COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "ES", name: "Spain" },
  { code: "IT", name: "Italy" },
  { code: "NL", name: "Netherlands" },
  { code: "BE", name: "Belgium" },
  { code: "CH", name: "Switzerland" },
  { code: "AT", name: "Austria" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "PL", name: "Poland" },
  { code: "CZ", name: "Czech Republic" },
  { code: "PT", name: "Portugal" },
  { code: "GR", name: "Greece" },
  { code: "IE", name: "Ireland" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "CN", name: "China" },
  { code: "IN", name: "India" },
  { code: "SG", name: "Singapore" },
  { code: "HK", name: "Hong Kong" },
  { code: "TW", name: "Taiwan" },
  { code: "MY", name: "Malaysia" },
  { code: "TH", name: "Thailand" },
  { code: "ID", name: "Indonesia" },
  { code: "PH", name: "Philippines" },
  { code: "VN", name: "Vietnam" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "AR", name: "Argentina" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "PE", name: "Peru" },
  { code: "ZA", name: "South Africa" },
  { code: "EG", name: "Egypt" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "IL", name: "Israel" },
  { code: "TR", name: "Turkey" },
  { code: "RU", name: "Russia" },
  { code: "UA", name: "Ukraine" },
  { code: "NZ", name: "New Zealand" },
] as const

// Languages with their codes
export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "it", name: "Italian" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "pt", name: "Portuguese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "zh", name: "Chinese" },
  { code: "ru", name: "Russian" },
  { code: "tr", name: "Turkish" },
  { code: "pl", name: "Polish" },
  { code: "nl", name: "Dutch" },
  { code: "da", name: "Danish" },
  { code: "sv", name: "Swedish" },
  { code: "no", name: "Norwegian" },
  { code: "fi", name: "Finnish" },
] as const
